vim.opt.hlsearch = false
vim.opt.hidden = true
vim.opt.smoothscroll = true
vim.wo.number = true
vim.wo.relativenumber = true
vim.opt.mouse = "a"
vim.opt.breakindent = true
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.updatetime = 250
vim.opt.signcolumn = "yes"
vim.opt.termguicolors = true
vim.opt.completeopt = { "menu", "menuone", "noselect" } -- 'menu' is new
vim.opt.spelllang = "en_us"
vim.opt.spell = true
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 4
vim.opt.tabstop = 4
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.laststatus = 2
vim.opt.autoread = true
vim.opt.wildmenu = true
vim.opt.grepprg = "rg --vimgrep --smart-case --follow"
vim.opt.conceallevel = 1
